backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: 'events'
    label: 'Events'
    files:
      - file: 'src/pages/events/events.md'
        label: 'Events'
        name: 'events'
        fields:
          - {
              label: 'Event',
              name: 'event',
              widget: list,
              fields:
                [
                  { label: 'Name', name: 'name', widget: string },
                  { label: 'Date', name: 'date', widget: datetime },
                  { label: 'URL', name: 'url', widget: string },
                  { label: 'Address', name: 'address', widget: string },
                ],
            }

  - name: 'slider'
    label: 'Home Page'
    files:
      - file: 'src/pages/content/slider.md'
        label: 'Slider'
        name: 'slider'
        fields:
          - { name: 'title', label: 'Title', widget: string }
          - { label: Image, name: image, widget: image }
