backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: 'events'
    label: 'Events'
    files:
      - file: 'src/pages/events/events.md'
        label: 'Events'
        name: 'events'
        fields:
          - {
              label: 'Event',
              name: 'event',
              widget: list,
              fields:
                [
                  { label: 'Name', name: 'name', widget: string },
                  { label: 'Date', name: 'date', widget: datetime },
                  { label: 'URL', name: 'url', widget: string },
                  { label: 'Address', name: 'address', widget: string },
                ],
            }

  - name: 'homePage'
    label: 'Home Page'
    files:
      - file: 'src/pages/content/slider.md'
        label: 'Image Slider'
        name: 'slider'
        fields:
          - {
              label: 'Slider Images',
              name: 'image',
              widget: list,
              fields:
                [
                  { label: Image, name: image, widget: image },
                  { name: 'description', label: 'description', widget: string },
                ],
            }
